### ISSUE TITLE
materialized: incremental fails if table does not already exist

### ISSUE THREAD

**Issue by duncancfraser** [analyst-collective/dbt#130]
When setting a table to incremental, dbt throws the following error if the table does not already exist:

```
aggregates not allowed in WHERE clause
```

  Ideally, when set to incremental, dbt would check if the table exists, and if it does not, build the table. It works fine in cases where the table already exists.

**Comment by jthandy** [comment]
Agree--100%, that is the intended goal. If it's not working in the case of the table not yet existing that's a bug.

**Comment by drewbanin** [comment]
@duncancfraser -- this is supposed to work! I could foresee an issue where dbt would get confused if the table schema changes between dbt incremental runs, but there's definitely logic in there to create a new table if one doesn't exist for incremental models.

Can you send me (here or via email) the relevant output from `logs/dbt.log` -- would love to get this working properly.

**Comment by duncancfraser** [comment]
@drewbanin sure thing! 

```
create temporary table "address_lookup__dbt_incremental_tmp" diststyle key distkey ("address_id") compound sortkey ("address_id", "zipcode") as (
    select * from (
        with __dbt__CTE__spree_countries as
  (select *
   from storefront.spree_countries),
     __dbt__CTE__dma_zip_map as
  (select *
   from maps.zip_to_dma),
     __dbt__CTE__zip_code_tax_rates as
  (select *
   from storefront.zip_code_tax_rates),
     __dbt__CTE__spree_states as
  (select *
   from storefront.spree_states),
     __dbt__CTE__household_by_dma_2015 as
  (select *
   from maps.hh_dma_2015_stats ),
     __dbt__CTE__courier_zones as
  (select *
   from maps.courier_zones),
     __dbt__CTE__spree_addresses as
  (select *,
          case
              when address1 similar to '%(45 Bond|47-09 30th St|37 E 18th|37 East 18th|151 W. 26th St.|151 West 26th St.)%' then true
              else false
          end as is_casper_address
   from storefront.spree_addresses)
select sa.id as address_id,
       sa.updated_at,
       sa.firstname,
       sa.lastname,
       sa.address1,
       sa.address2,
       sa.city,
       sa.is_casper_address,
       sa.zipcode,
       cty.iso as country_iso,
       cty.iso3 as country_iso3,
       cty.name as country,
       sst.name as state,
       sst.abbr as state_code,
       dmz.dma_name,
       dmz.dma_code,
       cz.carrier_name as courier_name,
       cz.courier_region,
       cz.max_delivery_date,
       cz.min_delivery_date,
       cz.status as courier_zone_status,
       ztr.tax_region_code,
       ztr.tax_region_name,
       ztr.combined_rate as combined_tax_rate,
       ztr.state_rate as state_tax_rate,
       ztr.county_rate as country_tax_rate,
       ztr.city_rate as city_tax_rate,
       ztr.special_rate as special_tax_rate,
       hh.household_count,
       hh.population_12_and_older,
       hh.household_rank
from __dbt__CTE__spree_addresses sa
left join __dbt__CTE__spree_countries cty on sa.country_id = cty.id
left join __dbt__CTE__spree_states sst on sst.id = sa.state_id
left join __dbt__CTE__dma_zip_map dmz on dmz.zip = sa.zipcode
left join __dbt__CTE__courier_zones cz on cz.zip_code = sa.zipcode
left join __dbt__CTE__zip_code_tax_rates ztr on ztr.zip_code = sa.zipcode
left join __dbt__CTE__household_by_dma_2015 hh on hh.dma_code = dmz.dma_code
    ) as tmp limit 0
);

create table if not exists "analytics"."address_lookup" (like "address_lookup__dbt_incremental_tmp");


delete from "analytics"."address_lookup" where  (address_id) in (
    with dbt_delete_sbq as (
        with __dbt__CTE__spree_countries as
  (select *
   from storefront.spree_countries),
     __dbt__CTE__dma_zip_map as
  (select *
   from maps.zip_to_dma),
     __dbt__CTE__zip_code_tax_rates as
  (select *
   from storefront.zip_code_tax_rates),
     __dbt__CTE__spree_states as
  (select *
   from storefront.spree_states),
     __dbt__CTE__household_by_dma_2015 as
  (select *
   from maps.hh_dma_2015_stats ),
     __dbt__CTE__courier_zones as
  (select *
   from maps.courier_zones),
     __dbt__CTE__spree_addresses as
  (select *,
          case
              when address1 similar to '%(45 Bond|47-09 30th St|37 E 18th|37 East 18th|151 W. 26th St.|151 West 26th St.)%' then true
              else false
          end as is_casper_address
   from storefront.spree_addresses)
select sa.id as address_id,
       sa.updated_at,
       sa.firstname,
       sa.lastname,
       sa.address1,
       sa.address2,
       sa.city,
       sa.is_casper_address,
       sa.zipcode,
       cty.iso as country_iso,
       cty.iso3 as country_iso3,
       cty.name as country,
       sst.name as state,
       sst.abbr as state_code,
       dmz.dma_name,
       dmz.dma_code,
       cz.carrier_name as courier_name,
       cz.courier_region,
       cz.max_delivery_date,
       cz.min_delivery_date,
       cz.status as courier_zone_status,
       ztr.tax_region_code,
       ztr.tax_region_name,
       ztr.combined_rate as combined_tax_rate,
       ztr.state_rate as state_tax_rate,
       ztr.county_rate as country_tax_rate,
       ztr.city_rate as city_tax_rate,
       ztr.special_rate as special_tax_rate,
       hh.household_count,
       hh.population_12_and_older,
       hh.household_rank
from __dbt__CTE__spree_addresses sa
left join __dbt__CTE__spree_countries cty on sa.country_id = cty.id
left join __dbt__CTE__spree_states sst on sst.id = sa.state_id
left join __dbt__CTE__dma_zip_map dmz on dmz.zip = sa.zipcode
left join __dbt__CTE__courier_zones cz on cz.zip_code = sa.zipcode
left join __dbt__CTE__zip_code_tax_rates ztr on ztr.zip_code = sa.zipcode
left join __dbt__CTE__household_by_dma_2015 hh on hh.dma_code = dmz.dma_code
    )
    select (address_id) from dbt_delete_sbq
    where (updated_at > (select max(updated_at) from "analytics"."address_lookup")) or (updated_at > (select max(updated_at) from "analytics"."address_lookup")) is null
);


insert into "analytics"."address_lookup" (
    with dbt_incr_sbq as (
        with __dbt__CTE__spree_countries as
  (select *
   from storefront.spree_countries),
     __dbt__CTE__dma_zip_map as
  (select *
   from maps.zip_to_dma),
     __dbt__CTE__zip_code_tax_rates as
  (select *
   from storefront.zip_code_tax_rates),
     __dbt__CTE__spree_states as
  (select *
   from storefront.spree_states),
     __dbt__CTE__household_by_dma_2015 as
  (select *
   from maps.hh_dma_2015_stats ),
     __dbt__CTE__courier_zones as
  (select *
   from maps.courier_zones),
     __dbt__CTE__spree_addresses as
  (select *,
          case
              when address1 similar to '%(45 Bond|47-09 30th St|37 E 18th|37 East 18th|151 W. 26th St.|151 West 26th St.)%' then true
              else false
          end as is_casper_address
   from storefront.spree_addresses)
select sa.id as address_id,
       sa.updated_at,
       sa.firstname,
       sa.lastname,
       sa.address1,
       sa.address2,
       sa.city,
       sa.is_casper_address,
       sa.zipcode,
       cty.iso as country_iso,
       cty.iso3 as country_iso3,
       cty.name as country,
       sst.name as state,
       sst.abbr as state_code,
       dmz.dma_name,
       dmz.dma_code,
       cz.carrier_name as courier_name,
       cz.courier_region,
       cz.max_delivery_date,
       cz.min_delivery_date,
       cz.status as courier_zone_status,
       ztr.tax_region_code,
       ztr.tax_region_name,
       ztr.combined_rate as combined_tax_rate,
       ztr.state_rate as state_tax_rate,
       ztr.county_rate as country_tax_rate,
       ztr.city_rate as city_tax_rate,
       ztr.special_rate as special_tax_rate,
       hh.household_count,
       hh.population_12_and_older,
       hh.household_rank
from __dbt__CTE__spree_addresses sa
left join __dbt__CTE__spree_countries cty on sa.country_id = cty.id
left join __dbt__CTE__spree_states sst on sst.id = sa.state_id
left join __dbt__CTE__dma_zip_map dmz on dmz.zip = sa.zipcode
left join __dbt__CTE__courier_zones cz on cz.zip_code = sa.zipcode
left join __dbt__CTE__zip_code_tax_rates ztr on ztr.zip_code = sa.zipcode
left join __dbt__CTE__household_by_dma_2015 hh on hh.dma_code = dmz.dma_code
    )
    select * from dbt_incr_sbq
    where (updated_at > (select max(updated_at) from "analytics"."address_lookup")) or (updated_at > (select max(updated_at) from "analytics"."address_lookup")) is null
);
    
2016-08-28 16:45:40,173 - dbt.schema - ERROR - Thread-2 - Error running SQL: -- Compiled by DBT



create temporary table "address_lookup__dbt_incremental_tmp" diststyle key distkey ("address_id") compound sortkey ("address_id", "zipcode") as (
    select * from (
        with __dbt__CTE__spree_countries as
  (select *
   from storefront.spree_countries),
     __dbt__CTE__dma_zip_map as
  (select *
   from maps.zip_to_dma),
     __dbt__CTE__zip_code_tax_rates as
  (select *
   from storefront.zip_code_tax_rates),
     __dbt__CTE__spree_states as
  (select *
   from storefront.spree_states),
     __dbt__CTE__household_by_dma_2015 as
  (select *
   from maps.hh_dma_2015_stats ),
     __dbt__CTE__courier_zones as
  (select *
   from maps.courier_zones),
     __dbt__CTE__spree_addresses as
  (select *,
          case
              when address1 similar to '%(45 Bond|47-09 30th St|37 E 18th|37 East 18th|151 W. 26th St.|151 West 26th St.)%' then true
              else false
          end as is_casper_address
   from storefront.spree_addresses)
select sa.id as address_id,
       sa.updated_at,
       sa.firstname,
       sa.lastname,
       sa.address1,
       sa.address2,
       sa.city,
       sa.is_casper_address,
       sa.zipcode,
       cty.iso as country_iso,
       cty.iso3 as country_iso3,
       cty.name as country,
       sst.name as state,
       sst.abbr as state_code,
       dmz.dma_name,
       dmz.dma_code,
       cz.carrier_name as courier_name,
       cz.courier_region,
       cz.max_delivery_date,
       cz.min_delivery_date,
       cz.status as courier_zone_status,
       ztr.tax_region_code,
       ztr.tax_region_name,
       ztr.combined_rate as combined_tax_rate,
       ztr.state_rate as state_tax_rate,
       ztr.county_rate as country_tax_rate,
       ztr.city_rate as city_tax_rate,
       ztr.special_rate as special_tax_rate,
       hh.household_count,
       hh.population_12_and_older,
       hh.household_rank
from __dbt__CTE__spree_addresses sa
left join __dbt__CTE__spree_countries cty on sa.country_id = cty.id
left join __dbt__CTE__spree_states sst on sst.id = sa.state_id
left join __dbt__CTE__dma_zip_map dmz on dmz.zip = sa.zipcode
left join __dbt__CTE__courier_zones cz on cz.zip_code = sa.zipcode
left join __dbt__CTE__zip_code_tax_rates ztr on ztr.zip_code = sa.zipcode
left join __dbt__CTE__household_by_dma_2015 hh on hh.dma_code = dmz.dma_code
    ) as tmp limit 0
);

create table if not exists "analytics"."address_lookup" (like "address_lookup__dbt_incremental_tmp");


delete from "analytics"."address_lookup" where  (address_id) in (
    with dbt_delete_sbq as (
        with __dbt__CTE__spree_countries as
  (select *
   from storefront.spree_countries),
     __dbt__CTE__dma_zip_map as
  (select *
   from maps.zip_to_dma),
     __dbt__CTE__zip_code_tax_rates as
  (select *
   from storefront.zip_code_tax_rates),
     __dbt__CTE__spree_states as
  (select *
   from storefront.spree_states),
     __dbt__CTE__household_by_dma_2015 as
  (select *
   from maps.hh_dma_2015_stats ),
     __dbt__CTE__courier_zones as
  (select *
   from maps.courier_zones),
     __dbt__CTE__spree_addresses as
  (select *,
          case
              when address1 similar to '%(45 Bond|47-09 30th St|37 E 18th|37 East 18th|151 W. 26th St.|151 West 26th St.)%' then true
              else false
          end as is_casper_address
   from storefront.spree_addresses)
select sa.id as address_id,
       sa.updated_at,
       sa.firstname,
       sa.lastname,
       sa.address1,
       sa.address2,
       sa.city,
       sa.is_casper_address,
       sa.zipcode,
       cty.iso as country_iso,
       cty.iso3 as country_iso3,
       cty.name as country,
       sst.name as state,
       sst.abbr as state_code,
       dmz.dma_name,
       dmz.dma_code,
       cz.carrier_name as courier_name,
       cz.courier_region,
       cz.max_delivery_date,
       cz.min_delivery_date,
       cz.status as courier_zone_status,
       ztr.tax_region_code,
       ztr.tax_region_name,
       ztr.combined_rate as combined_tax_rate,
       ztr.state_rate as state_tax_rate,
       ztr.county_rate as country_tax_rate,
       ztr.city_rate as city_tax_rate,
       ztr.special_rate as special_tax_rate,
       hh.household_count,
       hh.population_12_and_older,
       hh.household_rank
from __dbt__CTE__spree_addresses sa
left join __dbt__CTE__spree_countries cty on sa.country_id = cty.id
left join __dbt__CTE__spree_states sst on sst.id = sa.state_id
left join __dbt__CTE__dma_zip_map dmz on dmz.zip = sa.zipcode
left join __dbt__CTE__courier_zones cz on cz.zip_code = sa.zipcode
left join __dbt__CTE__zip_code_tax_rates ztr on ztr.zip_code = sa.zipcode
left join __dbt__CTE__household_by_dma_2015 hh on hh.dma_code = dmz.dma_code
    )
    select (address_id) from dbt_delete_sbq
    where (updated_at > (select max(updated_at) from "analytics"."address_lookup")) or (updated_at > (select max(updated_at) from "analytics"."address_lookup")) is null
);


insert into "analytics"."address_lookup" (
    with dbt_incr_sbq as (
        with __dbt__CTE__spree_countries as
  (select *
   from storefront.spree_countries),
     __dbt__CTE__dma_zip_map as
  (select *
   from maps.zip_to_dma),
     __dbt__CTE__zip_code_tax_rates as
  (select *
   from storefront.zip_code_tax_rates),
     __dbt__CTE__spree_states as
  (select *
   from storefront.spree_states),
     __dbt__CTE__household_by_dma_2015 as
  (select *
   from maps.hh_dma_2015_stats ),
     __dbt__CTE__courier_zones as
  (select *
   from maps.courier_zones),
     __dbt__CTE__spree_addresses as
  (select *,
          case
              when address1 similar to '%(45 Bond|47-09 30th St|37 E 18th|37 East 18th|151 W. 26th St.|151 West 26th St.)%' then true
              else false
          end as is_casper_address
   from storefront.spree_addresses)
select sa.id as address_id,
       sa.updated_at,
       sa.firstname,
       sa.lastname,
       sa.address1,
       sa.address2,
       sa.city,
       sa.is_casper_address,
       sa.zipcode,
       cty.iso as country_iso,
       cty.iso3 as country_iso3,
       cty.name as country,
       sst.name as state,
       sst.abbr as state_code,
       dmz.dma_name,
       dmz.dma_code,
       cz.carrier_name as courier_name,
       cz.courier_region,
       cz.max_delivery_date,
       cz.min_delivery_date,
       cz.status as courier_zone_status,
       ztr.tax_region_code,
       ztr.tax_region_name,
       ztr.combined_rate as combined_tax_rate,
       ztr.state_rate as state_tax_rate,
       ztr.county_rate as country_tax_rate,
       ztr.city_rate as city_tax_rate,
       ztr.special_rate as special_tax_rate,
       hh.household_count,
       hh.population_12_and_older,
       hh.household_rank
from __dbt__CTE__spree_addresses sa
left join __dbt__CTE__spree_countries cty on sa.country_id = cty.id
left join __dbt__CTE__spree_states sst on sst.id = sa.state_id
left join __dbt__CTE__dma_zip_map dmz on dmz.zip = sa.zipcode
left join __dbt__CTE__courier_zones cz on cz.zip_code = sa.zipcode
left join __dbt__CTE__zip_code_tax_rates ztr on ztr.zip_code = sa.zipcode
left join __dbt__CTE__household_by_dma_2015 hh on hh.dma_code = dmz.dma_code
    )
    select * from dbt_incr_sbq
    where (updated_at > (select max(updated_at) from "analytics"."address_lookup")) or (updated_at > (select max(updated_at) from "analytics"."address_lookup")) is null
);
    
Traceback (most recent call last):
  File "/Users/duncan.fraser/anaconda2/lib/python2.7/site-packages/dbt/schema.py", line 61, in execute
    cursor.execute(sql)
ProgrammingError: aggregates not allowed in WHERE clause

2016-08-28 16:45:40,173 - dbt.schema - DEBUG - Thread-2 - rolling back connection
2016-08-28 16:45:40,174 - dbt.runner - ERROR - Thread-2 - Error executing target/build/Casper/fat/address_lookup.sql
aggregates not allowed in WHERE clause
Traceback (most recent call last):
  File "/Users/duncan.fraser/anaconda2/lib/python2.7/site-packages/dbt/runner.py", line 239, in safe_execute_model
    status = self.execute_model(runner, model)
  File "/Users/duncan.fraser/anaconda2/lib/python2.7/site-packages/dbt/runner.py", line 229, in execute_model
    result = runner.execute(self.schema, self.target, model)
  File "/Users/duncan.fraser/anaconda2/lib/python2.7/site-packages/dbt/runner.py", line 102, in execute
    status = schema.execute_and_handle_permissions(model.contents, model.name)
  File "/Users/duncan.fraser/anaconda2/lib/python2.7/site-packages/dbt/schema.py", line 99, in execute_and_handle_permissions
    raise e
ProgrammingError: aggregates not allowed in WHERE clause
```

**Comment by drewbanin** [comment]
@duncancfraser this is a strange one -- the above SQL should work as expected. Moreover, there aren't any aggregates in any of the where clauses, so the `aggregates not allowed in WHERE clause` error message doesn't seem like a reasonable one. Are you still having a problem with this?

**Comment by drewbanin** [comment]
re: "work as expected" -- if you run the `SELECT` part of the query inside of the `INSERT` statement, you get back a result set without any errors! strange

**Comment by drewbanin** [comment]
Closing this!
