### ISSUE TITLE
Issue when using dbt on Windows

### ISSUE THREAD

**Issue by akashagrawal13** [analyst-collective/dbt#17]
Followed all steps, and encountered this stack trace when running `dbt compile`:

```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\dbt.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\dbt\main.py", line 37, in main
    parsed.cls(args=parsed, project=proj).run()
  File "c:\python27\lib\site-packages\dbt\task\compile.py", line 102, in run
    self.__compile(src_index)
  File "c:\python27\lib\site-packages\dbt\task\compile.py", line 92, in __compile
    template = jinja.get_template(f)
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 812, in get_t                               emplate
    return self._load_template(name, self.make_globals(globals))
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 774, in _load                               _template
    cache_key = self.loader.get_source(self, name)[1]
  File "c:\python27\lib\site-packages\jinja2\loaders.py", line 168, in get_sourc                               e
    pieces = split_template_path(template)
  File "c:\python27\lib\site-packages\jinja2\loaders.py", line 31, in split_temp                               late_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email\emails_denormalized.sql
```

**Comment by drewbanin** [comment]
need a windows box to debug this on

**Comment by jthandy** [comment]
this is being handled by the docker install process. we're actively choosing not to debug install problems on particular environments.
