### ISSUE TITLE
better error messages for schema testing

### ISSUE THREAD

**Issue by drewbanin** [analyst-collective/dbt#240]
Invalid schema tests should show helpful errors. At the very least, show which tests failed to compile.

```
Traceback (most recent call last):
  File "/Users/tristan/dev/venv/bin/dbt", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/tristan/dev/dbt/scripts/dbt", line 8, in <module>
    dbt.main.main(sys.argv[1:])
  File "/Users/tristan/dev/dbt/dbt/main.py", line 41, in main
    handle(args)
  File "/Users/tristan/dev/dbt/dbt/main.py", line 143, in handle
    task.run()
  File "/Users/tristan/dev/dbt/dbt/task/run.py", line 28, in run
    graph_type = self.compile()
  File "/Users/tristan/dev/dbt/dbt/task/run.py", line 20, in compile
    results = compiler.compile(self.args.dry)
  File "/Users/tristan/dev/dbt/dbt/compilation.py", line 399, in compile
    written_schema_tests = self.compile_schema_tests(linker)
  File "/Users/tristan/dev/dbt/dbt/compilation.py", line 324, in compile_schema_tests
    schema_tests.extend(schema.compile()) # compiling a SchemaFile returns >= 0 SchemaTest models
  File "/Users/tristan/dev/dbt/dbt/model.py", line 556, in compile
    for params in constraint_data:
TypeError: 'NoneType' object is not iterable
```

**Comment by drewbanin** [comment]
fixed here: https://github.com/analyst-collective/dbt/pull/243
