### ISSUE TITLE
compilation error when var() value was null

### ISSUE THREAD

**Issue by jthandy** [analyst-collective/dbt#241]
I forgot to define the right values for a var. This was in my `dbt_project.yml`:

`ads_insights_actions_values_table:                     #todo`

Understood that this should fail, but this is not how it should fail. I got the following error:

```
(venv)Tristans-MacBook-Pro:analytics tristan$ dbt compile
Traceback (most recent call last):
  File "/Users/tristan/dev/venv/bin/dbt", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/tristan/dev/dbt/scripts/dbt", line 8, in <module>
    dbt.main.main(sys.argv[1:])
  File "/Users/tristan/dev/dbt/dbt/main.py", line 41, in main
    handle(args)
  File "/Users/tristan/dev/dbt/dbt/main.py", line 143, in handle
    task.run()
  File "/Users/tristan/dev/dbt/dbt/task/compile.py", line 19, in run
    results = compiler.compile(dry=self.args.dry)
  File "/Users/tristan/dev/dbt/dbt/compilation.py", line 396, in compile
    compiled_models, written_models = self.compile_models(linker, enabled_models)
  File "/Users/tristan/dev/dbt/dbt/compilation.py", line 281, in compile_models
    compiled_models = {model: self.compile_model(linker, model, models) for model in models}
  File "/Users/tristan/dev/dbt/dbt/compilation.py", line 281, in <dictcomp>
    compiled_models = {model: self.compile_model(linker, model, models) for model in models}
  File "/Users/tristan/dev/dbt/dbt/compilation.py", line 203, in compile_model
    rendered = template.render(context)
  File "/Users/tristan/dev/venv/lib/python3.4/site-packages/Jinja2-2.8-py3.4.egg/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/tristan/dev/venv/lib/python3.4/site-packages/Jinja2-2.8-py3.4.egg/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tristan/dev/venv/lib/python3.4/site-packages/Jinja2-2.8-py3.4.egg/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/tristan/dev/client/[client_name]/analytics/dbt_modules/facebook-ads/models/stitch/base/fb_ads_insights_actions_values.sql", line 3, in top-level template code
    select * from {{ var('ads_insights_actions_values_table') }}
  File "/Users/tristan/dev/dbt/dbt/utils.py", line 53, in __call__
    compiled = self.model.compile_string(self.context, raw)
  File "/Users/tristan/dev/dbt/dbt/model.py", line 303, in compile_string
    template = env.from_string(string, globals=ctx)
  File "/Users/tristan/dev/venv/lib/python3.4/site-packages/Jinja2-2.8-py3.4.egg/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/tristan/dev/venv/lib/python3.4/site-packages/Jinja2-2.8-py3.4.egg/jinja2/optimizer.py", line 27, in optimize
    return optimizer.visit(node)
  File "/Users/tristan/dev/venv/lib/python3.4/site-packages/Jinja2-2.8-py3.4.egg/jinja2/visitor.py", line 39, in visit
    return self.generic_visit(node, *args, **kwargs)
  File "/Users/tristan/dev/venv/lib/python3.4/site-packages/Jinja2-2.8-py3.4.egg/jinja2/visitor.py", line 59, in generic_visit
    for field, old_value in node.iter_fields():
AttributeError: 'NoneType' object has no attribute 'iter_fields'
```

**Comment by drewbanin** [comment]
this was fixed here: https://github.com/analyst-collective/dbt/pull/216 ..... kind of. The fix doesn't account will interpolate `None` into the `ads_insights_actions_values_table` var. That's probably not right. We can make this a compiler error

**Comment by jthandy** [comment]
yeah when a variable actually isn't specified there is a really nice compiler error message. should be the same here. this was challenging for me to track down.

**Comment by drewbanin** [comment]
quick fix here: https://github.com/analyst-collective/dbt/pull/242/commits/59eff6067c93b1dd938ed3a6a2286e6fa3d50026

Going out in "minor improvements" milestone
